# config.yml to define paths to the local pediatric_cancer_atlas_profiling repo
paths:
  pediatric_cancer_atlas_profiling_path: 'REPLACE/WITH/YOUR/OWN/PATH' # REPLACE WITH YOUR OWN LOCAL PATH
  sc_features_path: 'REPLACE/WITH/YOUR/OWN/PATH' # REPLACE WITH YOUR OWN LOCAL PATH
  software_path: 'REPLACE/WITH/YOUR/OWN/PATH'

data:
  input_channel_keys: ["OrigBrightfield"]
  target_channel_keys: ["OrigDNA", "OrigER", "OrigAGP", "OrigMito", "OrigRNA"]