name: speckle_analysis_processing
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.10
  - conda-forge::pip
  - conda-forge::seaborn
  - conda-forge::matplotlib
  - conda-forge::jupyter
  - conda-forge::pre_commit
  - conda-forge::pandas
  - conda-forge::numpy
  - conda-forge::pathlib2
  - conda-forge::scikit-learn
  - conda-forge::opencv
  - conda-forge::pyarrow
  - conda-forge::ipython
  - conda-forge::notebook
  - conda-forge::minepy
  - pip:
    - mlflow
